### ISSUE TITLE
Config settings / import refactoring

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#393]
We've been discussing reworking the dataset config along with simplifying the code/API. The following are desirable:
- JSON schema driven config editor
- Config editable from the API (enables quick edits to text templates by non-experts for example)
- Human editable on disk
- Retain current dir/settings structure
- Reduce current YAML->JSON->SQL->JSON to something more sane (only data in tables, not config)
- Things like stored queries written back to config (via the API)
- No import required unless data needs to be read into tables/summarised.
- Only needed import actions performed after config change

This issue is an attempt at a strawman proposal for making this happen.
- [x] Define the JSON object that the client needs for config. Call it the "JSON config object". This definition may take the form of python code that transforms the YAML input config? (BJ?)
- [x] Use this to serve the JSON config object over the API (YAML read and re-transformed on server boot and any API writing operation? If syntax error then use last successful but pass on message?)
- [x] Convert the client to use this JSON config object
- [x] Remove all import code that generates now unneeded tables
- [x] Pass categories down in JSON config object
- [x] Restore summary info and ref genome tracks in JSON config object
- [x] Restore tree info in JSON config object
- [ ] On each import record the JSON config object used
- [ ] On every YAML read do a diff to the one used at import. If import-needed changes are detected then insert information about that into the JSON config object for the client to tell the user and/or add a button to press to do the work.
- [x] Add API method for editing config that writes back to the YAML and triggers YAML read.
- [ ] ~~Add client code for JSON schema driven config editor~~ *We have YAML editing which is enough for now*

We should also take this opportunity to remove as many config options as possible....
This is just for discussion for now, but I think a scheme like this could work well.

**Comment by benjeffery** [comment]
On the json_config branch I have been working on a proof-of-concept. 

- The client on this branch requests JSON config from the server. The server reads the YAML files to serve this request in https://github.com/cggh/panoptes/blob/json_config/servermodule/panoptesserver/importer/readConfig.py (this would be calculated on server boot in a full system, hence not quite ticking box 2!). 

- The client then uses this config. Not all client features work yet (hence not quite ticking box 3!)

But it works! This means the following tables and all import code for them can be deleted: | 2D_propertycatalog, 2D_tablecatalog, chromosomes, customdatacatalog, externallinks, graphs, introviews, propertycatalog, relations, settings, summaryvalues, tablebasedsummaryvalues, tablecatalog.

**Comment by benjeffery** [comment]
#447 is roughly complete, moving to #452

**Comment by benjeffery** [comment]
This work is now on master. The client is using the JSON config object and can modify it, with changes being persisted to the YAML.
Next step is to cut all now unneeded routines and tables out of the server import code. This should be done with possible Monet usage in mind.

**Comment by benjeffery** [comment]
The only remaining work for this epic is the detection of "import needed" changes, which I'm happy to live without for now.
